apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: full-install
  namespace: istio-system
spec:
  istio:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      mtls:
        enabled: false
      disablePolicyChecks: true
      policyCheckFailOpen: false
      # imagePullSecrets:
      #   - MyPullSecret

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        # autoscaleMin: 1
        # autoscaleMax: 3
      istio-ingressgateway:
        autoscaleEnabled: false
        # autoscaleMin: 1
        # autoscaleMax: 3

    mixer:
      policy:
        autoscaleEnabled: false
      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
      autoscaleEnabled: false
      traceSampling: 100

    kiali:
      enabled: true
      dashboard:
        viewOnlyMode: true
      ingress:
        enabled: true

    grafana:
      enabled: true

    tracing:
      enabled: true
      jaeger:
        template: all-in-one
        # For Production only
        # template: production-elasticsearch     
        # elasticsearch:
        #   nodeCount: 3
        #   redundancyPolicy:
        #   resources:
        #     requests:
        #       cpu: "1"
        #       memory: "16Gi"
        #     limits:
        #       cpu: "1"
        #       memory: "16Gi"

  threeScale:
    enabled: true
    PARAM_THREESCALE_LISTEN_ADDR: 3333
    PARAM_THREESCALE_LOG_LEVEL: info
    PARAM_THREESCALE_LOG_JSON: true
    PARAM_THREESCALE_LOG_GRPC: false
    PARAM_THREESCALE_REPORT_METRICS: true
    PARAM_THREESCALE_METRICS_PORT: 8080
    PARAM_THREESCALE_CACHE_TTL_SECONDS: 300
    PARAM_THREESCALE_CACHE_REFRESH_SECONDS: 180
    PARAM_THREESCALE_CACHE_ENTRIES_MAX: 1000
    PARAM_THREESCALE_CACHE_REFRESH_RETRIES: 1
    PARAM_THREESCALE_ALLOW_INSECURE_CONN: true
    PARAM_THREESCALE_CLIENT_TIMEOUT_SECONDS: 10
    PARAM_THREESCALE_GRPC_CONN_MAX_SECONDS: 60